package UDML.diagram.structure;

/*Generated by MPS */

import jetbrains.mps.smodel.runtime.ConceptPresentationAspectBase;
import jetbrains.mps.smodel.runtime.ConceptPresentation;
import org.jetbrains.annotations.Nullable;
import org.jetbrains.mps.openapi.language.SAbstractConcept;
import jetbrains.mps.smodel.runtime.ConceptPresentationBuilder;

public class ConceptPresentationAspectImpl extends ConceptPresentationAspectBase {
  private ConceptPresentation props_AssociationEdge;
  private ConceptPresentation props_ClassNode;
  private ConceptPresentation props_DiagramEdge;
  private ConceptPresentation props_DiagramNode;
  private ConceptPresentation props_UDMLClassDiagram;

  @Override
  @Nullable
  public ConceptPresentation getDescriptor(SAbstractConcept c) {
    StructureAspectDescriptor structureDescriptor = (StructureAspectDescriptor) myLanguageRuntime.getAspect(jetbrains.mps.smodel.runtime.StructureAspectDescriptor.class);
    switch (structureDescriptor.internalIndex(c)) {
      case LanguageConceptSwitch.AssociationEdge:
        if (props_AssociationEdge == null) {
          ConceptPresentationBuilder cpb = new ConceptPresentationBuilder();
          cpb.rawPresentation("AssociationEdge");
          props_AssociationEdge = cpb.create();
        }
        return props_AssociationEdge;
      case LanguageConceptSwitch.ClassNode:
        if (props_ClassNode == null) {
          ConceptPresentationBuilder cpb = new ConceptPresentationBuilder();
          cpb.presentationByReference(0x4a5be9b248944ea0L, 0x99e2bec8b6e617dbL, 0x35f6c4516a9e5007L, 0x35f6c4516a9e5009L, "reference", "", "");
          props_ClassNode = cpb.create();
        }
        return props_ClassNode;
      case LanguageConceptSwitch.DiagramEdge:
        if (props_DiagramEdge == null) {
          ConceptPresentationBuilder cpb = new ConceptPresentationBuilder();
          props_DiagramEdge = cpb.create();
        }
        return props_DiagramEdge;
      case LanguageConceptSwitch.DiagramNode:
        if (props_DiagramNode == null) {
          ConceptPresentationBuilder cpb = new ConceptPresentationBuilder();
          props_DiagramNode = cpb.create();
        }
        return props_DiagramNode;
      case LanguageConceptSwitch.UDMLClassDiagram:
        if (props_UDMLClassDiagram == null) {
          ConceptPresentationBuilder cpb = new ConceptPresentationBuilder();
          cpb.rawPresentation("UDMLClassDiagram");
          props_UDMLClassDiagram = cpb.create();
        }
        return props_UDMLClassDiagram;
    }
    return null;
  }
}
