package UDML.diagram.structure;

/*Generated by MPS */

import jetbrains.mps.lang.smodel.LanguageConceptIndex;
import jetbrains.mps.lang.smodel.LanguageConceptIndexBuilder;
import jetbrains.mps.smodel.adapter.ids.SConceptId;
import org.jetbrains.mps.openapi.language.SAbstractConcept;

public final class LanguageConceptSwitch {
  private final LanguageConceptIndex myIndex;
  public static final int AssociationEdge = 0;
  public static final int ClassNode = 1;
  public static final int DiagramEdge = 2;
  public static final int DiagramNode = 3;
  public static final int UDMLClassDiagram = 4;

  public LanguageConceptSwitch() {
    LanguageConceptIndexBuilder builder = new LanguageConceptIndexBuilder(0x4a5be9b248944ea0L, 0x99e2bec8b6e617dbL);
    builder.put(0x35f6c4516a9e500aL, AssociationEdge);
    builder.put(0x35f6c4516a9e5007L, ClassNode);
    builder.put(0x35f6c4516a9e5005L, DiagramEdge);
    builder.put(0x35f6c4516a9e5004L, DiagramNode);
    builder.put(0x35f6c4516a9d8ca0L, UDMLClassDiagram);
    myIndex = builder.seal();
  }

  /*package*/ int index(SConceptId cid) {
    return myIndex.index(cid);
  }

  public int index(SAbstractConcept concept) {
    return myIndex.index(concept);
  }
}
