package UDML.diagram.structure;

/*Generated by MPS */

import jetbrains.mps.smodel.runtime.BaseStructureAspectDescriptor;
import jetbrains.mps.smodel.runtime.ConceptDescriptor;
import java.util.Collection;
import java.util.Arrays;
import org.jetbrains.annotations.Nullable;
import jetbrains.mps.smodel.adapter.ids.SConceptId;
import org.jetbrains.mps.openapi.language.SAbstractConcept;
import jetbrains.mps.smodel.runtime.impl.ConceptDescriptorBuilder2;

public class StructureAspectDescriptor extends BaseStructureAspectDescriptor {
  /*package*/ final ConceptDescriptor myConceptAssociationEdge = createDescriptorForAssociationEdge();
  /*package*/ final ConceptDescriptor myConceptClassNode = createDescriptorForClassNode();
  /*package*/ final ConceptDescriptor myConceptDiagramEdge = createDescriptorForDiagramEdge();
  /*package*/ final ConceptDescriptor myConceptDiagramNode = createDescriptorForDiagramNode();
  /*package*/ final ConceptDescriptor myConceptUDMLClassDiagram = createDescriptorForUDMLClassDiagram();
  private final LanguageConceptSwitch myIndexSwitch;

  public StructureAspectDescriptor() {
    myIndexSwitch = new LanguageConceptSwitch();
  }


  @Override
  public void reportDependencies(jetbrains.mps.smodel.runtime.StructureAspectDescriptor.Dependencies deps) {
    deps.extendedLanguage(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, "jetbrains.mps.lang.core");
  }

  @Override
  public Collection<ConceptDescriptor> getDescriptors() {
    return Arrays.asList(myConceptAssociationEdge, myConceptClassNode, myConceptDiagramEdge, myConceptDiagramNode, myConceptUDMLClassDiagram);
  }

  @Override
  @Nullable
  public ConceptDescriptor getDescriptor(SConceptId id) {
    switch (myIndexSwitch.index(id)) {
      case LanguageConceptSwitch.AssociationEdge:
        return myConceptAssociationEdge;
      case LanguageConceptSwitch.ClassNode:
        return myConceptClassNode;
      case LanguageConceptSwitch.DiagramEdge:
        return myConceptDiagramEdge;
      case LanguageConceptSwitch.DiagramNode:
        return myConceptDiagramNode;
      case LanguageConceptSwitch.UDMLClassDiagram:
        return myConceptUDMLClassDiagram;
      default:
        return null;
    }
  }


  /*package*/ int internalIndex(SAbstractConcept c) {
    return myIndexSwitch.index(c);
  }

  private static ConceptDescriptor createDescriptorForAssociationEdge() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("UDML.diagram", "AssociationEdge", 0x4a5be9b248944ea0L, 0x99e2bec8b6e617dbL, 0x35f6c4516a9e500aL);
    b.class_(false, false, false);
    b.parent(0x4a5be9b248944ea0L, 0x99e2bec8b6e617dbL, 0x35f6c4516a9e5005L);
    b.origin("r:91f4cc49-3d99-4351-a567-8167c7320512(UDML.diagram.structure)/3888511182241157130");
    b.version(3);
    b.associate("represents", 0x35f6c4516a9e500cL).target(0xfd381d931dce4228L, 0xba53a4e0ecaf0da2L, 0x49e02d1c64bbef9dL).optional(false).origin("3888511182241157132").done();
    b.associate("source", 0x35f6c4516a9e500dL).target(0x4a5be9b248944ea0L, 0x99e2bec8b6e617dbL, 0x35f6c4516a9e5004L).optional(false).origin("3888511182241157133").done();
    b.associate("target", 0x35f6c4516a9e500eL).target(0x4a5be9b248944ea0L, 0x99e2bec8b6e617dbL, 0x35f6c4516a9e500aL).optional(false).origin("3888511182241157134").done();
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForClassNode() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("UDML.diagram", "ClassNode", 0x4a5be9b248944ea0L, 0x99e2bec8b6e617dbL, 0x35f6c4516a9e5007L);
    b.class_(false, false, false);
    b.parent(0x4a5be9b248944ea0L, 0x99e2bec8b6e617dbL, 0x35f6c4516a9e5004L);
    b.origin("r:91f4cc49-3d99-4351-a567-8167c7320512(UDML.diagram.structure)/3888511182241157127");
    b.version(3);
    b.associate("reference", 0x35f6c4516a9e5009L).target(0xfd381d931dce4228L, 0xba53a4e0ecaf0da2L, 0x49e02d1c64bbef7fL).optional(false).origin("3888511182241157129").done();
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForDiagramEdge() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("UDML.diagram", "DiagramEdge", 0x4a5be9b248944ea0L, 0x99e2bec8b6e617dbL, 0x35f6c4516a9e5005L);
    b.interface_();
    b.origin("r:91f4cc49-3d99-4351-a567-8167c7320512(UDML.diagram.structure)/3888511182241157125");
    b.version(3);
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForDiagramNode() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("UDML.diagram", "DiagramNode", 0x4a5be9b248944ea0L, 0x99e2bec8b6e617dbL, 0x35f6c4516a9e5004L);
    b.interface_();
    b.origin("r:91f4cc49-3d99-4351-a567-8167c7320512(UDML.diagram.structure)/3888511182241157124");
    b.version(3);
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForUDMLClassDiagram() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("UDML.diagram", "UDMLClassDiagram", 0x4a5be9b248944ea0L, 0x99e2bec8b6e617dbL, 0x35f6c4516a9d8ca0L);
    b.class_(false, false, true);
    b.origin("r:91f4cc49-3d99-4351-a567-8167c7320512(UDML.diagram.structure)/3888511182241107104");
    b.version(3);
    b.aggregate("node", 0x35f6c4516a9d8ca4L).target(0x4a5be9b248944ea0L, 0x99e2bec8b6e617dbL, 0x35f6c4516a9e5004L).optional(true).ordered(true).multiple(true).origin("3888511182241107108").done();
    b.aggregate("edge", 0x35f6c4516a9d8ca5L).target(0x4a5be9b248944ea0L, 0x99e2bec8b6e617dbL, 0x35f6c4516a9e5005L).optional(true).ordered(true).multiple(true).origin("3888511182241107109").done();
    return b.create();
  }
}
