package UDML.diagram.editor;

/*Generated by MPS */

import jetbrains.mps.nodeEditor.menus.substitute.SubstituteMenuBase;
import jetbrains.mps.lang.editor.menus.EditorMenuDescriptorBase;
import jetbrains.mps.smodel.SNodePointer;
import org.jetbrains.annotations.NotNull;
import java.util.List;
import jetbrains.mps.lang.editor.menus.MenuPart;
import jetbrains.mps.openapi.editor.menus.substitute.SubstituteMenuItem;
import jetbrains.mps.openapi.editor.menus.substitute.SubstituteMenuContext;
import java.util.ArrayList;
import jetbrains.mps.lang.editor.menus.substitute.ConstraintsFilteringSubstituteMenuPartDecorator;
import jetbrains.mps.lang.editor.menus.substitute.ReferenceScopeSubstituteMenuPart;
import jetbrains.mps.lang.editor.menus.ConceptMenusPart;
import java.util.Collection;
import org.jetbrains.mps.openapi.language.SAbstractConcept;
import jetbrains.mps.lang.editor.menus.substitute.DefaultSubstituteMenuLookup;
import jetbrains.mps.smodel.language.LanguageRegistry;
import org.jetbrains.mps.openapi.language.SConcept;
import jetbrains.mps.smodel.adapter.structure.MetaAdapterFactory;
import org.jetbrains.mps.openapi.language.SReferenceLink;

public class ClassNode_SubstituteMenu extends SubstituteMenuBase {
  public ClassNode_SubstituteMenu() {
    super(false, new EditorMenuDescriptorBase("default substitute menu for ClassNode. Generated from implicit smart reference attribute.", new SNodePointer("r:91f4cc49-3d99-4351-a567-8167c7320512(UDML.diagram.structure)", "3888511182241157127")));
  }
  @NotNull
  @Override
  protected List<MenuPart<SubstituteMenuItem, SubstituteMenuContext>> getParts(final SubstituteMenuContext _context) {
    List<MenuPart<SubstituteMenuItem, SubstituteMenuContext>> result = new ArrayList<MenuPart<SubstituteMenuItem, SubstituteMenuContext>>();
    result.add(new ConstraintsFilteringSubstituteMenuPartDecorator(new SMP_ReferenceScope_an0v2n_a(), CONCEPTS.ClassNode$FX));
    result.add(new SMP_Subconcepts_an0v2n_b());
    return result;
  }

  public class SMP_ReferenceScope_an0v2n_a extends ReferenceScopeSubstituteMenuPart {

    public SMP_ReferenceScope_an0v2n_a() {
      super(CONCEPTS.ClassNode$FX, LINKS.reference$wWXk, new EditorMenuDescriptorBase("reference scope substitute menu part", null));
    }

  }
  public class SMP_Subconcepts_an0v2n_b extends ConceptMenusPart<SubstituteMenuItem, SubstituteMenuContext> {
    public SMP_Subconcepts_an0v2n_b() {
      super(new EditorMenuDescriptorBase("include menus for all the direct subconcepts of " + "ClassNode", null));
    }

    @Override
    protected Collection<SAbstractConcept> getConcepts(final SubstituteMenuContext _context) {
      return getDirectDescendants(_context, CONCEPTS.ClassNode$FX);
    }

    @Override
    protected Collection<SubstituteMenuItem> createItemsForConcept(SubstituteMenuContext context, SAbstractConcept concept) {
      return context.createItems(new DefaultSubstituteMenuLookup(LanguageRegistry.getInstance(context.getEditorContext().getRepository()), concept));
    }
  }

  private static final class CONCEPTS {
    /*package*/ static final SConcept ClassNode$FX = MetaAdapterFactory.getConcept(0x4a5be9b248944ea0L, 0x99e2bec8b6e617dbL, 0x35f6c4516a9e5007L, "UDML.diagram.structure.ClassNode");
  }

  private static final class LINKS {
    /*package*/ static final SReferenceLink reference$wWXk = MetaAdapterFactory.getReferenceLink(0x4a5be9b248944ea0L, 0x99e2bec8b6e617dbL, 0x35f6c4516a9e5007L, 0x35f6c4516a9e5009L, "reference");
  }
}
