package UDML.rbac.structure;

/*Generated by MPS */

import jetbrains.mps.smodel.runtime.ConceptPresentationAspectBase;
import jetbrains.mps.smodel.runtime.ConceptPresentation;
import org.jetbrains.annotations.Nullable;
import org.jetbrains.mps.openapi.language.SAbstractConcept;
import jetbrains.mps.smodel.runtime.ConceptPresentationBuilder;

public class ConceptPresentationAspectImpl extends ConceptPresentationAspectBase {
  private ConceptPresentation props_DynamicSeparationOfDuty;
  private ConceptPresentation props_Permission;
  private ConceptPresentation props_Policy;
  private ConceptPresentation props_RBACAnnointern;
  private ConceptPresentation props_RbacRoot;
  private ConceptPresentation props_Role;
  private ConceptPresentation props_Session;
  private ConceptPresentation props_SoDConstraint;
  private ConceptPresentation props_StaticSeparationOfDuty;

  @Override
  @Nullable
  public ConceptPresentation getDescriptor(SAbstractConcept c) {
    StructureAspectDescriptor structureDescriptor = (StructureAspectDescriptor) myLanguageRuntime.getAspect(jetbrains.mps.smodel.runtime.StructureAspectDescriptor.class);
    switch (structureDescriptor.internalIndex(c)) {
      case LanguageConceptSwitch.DynamicSeparationOfDuty:
        if (props_DynamicSeparationOfDuty == null) {
          ConceptPresentationBuilder cpb = new ConceptPresentationBuilder();
          cpb.rawPresentation("DynamicSeparationOfDuty");
          props_DynamicSeparationOfDuty = cpb.create();
        }
        return props_DynamicSeparationOfDuty;
      case LanguageConceptSwitch.Permission:
        if (props_Permission == null) {
          ConceptPresentationBuilder cpb = new ConceptPresentationBuilder();
          cpb.rawPresentation("Permission");
          props_Permission = cpb.create();
        }
        return props_Permission;
      case LanguageConceptSwitch.Policy:
        if (props_Policy == null) {
          ConceptPresentationBuilder cpb = new ConceptPresentationBuilder();
          cpb.rawPresentation("Policy");
          props_Policy = cpb.create();
        }
        return props_Policy;
      case LanguageConceptSwitch.RBACAnnointern:
        if (props_RBACAnnointern == null) {
          ConceptPresentationBuilder cpb = new ConceptPresentationBuilder();
          props_RBACAnnointern = cpb.create();
        }
        return props_RBACAnnointern;
      case LanguageConceptSwitch.RbacRoot:
        if (props_RbacRoot == null) {
          ConceptPresentationBuilder cpb = new ConceptPresentationBuilder();
          cpb.rawPresentation("RbacRoot");
          props_RbacRoot = cpb.create();
        }
        return props_RbacRoot;
      case LanguageConceptSwitch.Role:
        if (props_Role == null) {
          ConceptPresentationBuilder cpb = new ConceptPresentationBuilder();
          cpb.rawPresentation("Role");
          props_Role = cpb.create();
        }
        return props_Role;
      case LanguageConceptSwitch.Session:
        if (props_Session == null) {
          ConceptPresentationBuilder cpb = new ConceptPresentationBuilder();
          cpb.rawPresentation("Session");
          props_Session = cpb.create();
        }
        return props_Session;
      case LanguageConceptSwitch.SoDConstraint:
        if (props_SoDConstraint == null) {
          ConceptPresentationBuilder cpb = new ConceptPresentationBuilder();
          cpb.rawPresentation("SoDConstraint");
          props_SoDConstraint = cpb.create();
        }
        return props_SoDConstraint;
      case LanguageConceptSwitch.StaticSeparationOfDuty:
        if (props_StaticSeparationOfDuty == null) {
          ConceptPresentationBuilder cpb = new ConceptPresentationBuilder();
          cpb.rawPresentation("StaticSeparationOfDuty");
          props_StaticSeparationOfDuty = cpb.create();
        }
        return props_StaticSeparationOfDuty;
    }
    return null;
  }
}
