package UDML.rbac.structure;

/*Generated by MPS */

import jetbrains.mps.smodel.runtime.EnumerationDescriptorBase;
import jetbrains.mps.smodel.runtime.EnumerationDescriptor;
import jetbrains.mps.lang.smodel.EnumerationLiteralsIndex;
import java.util.List;
import org.jetbrains.annotations.Nullable;
import org.jetbrains.annotations.NotNull;

public class EnumerationDescriptor_PermissonEnume extends EnumerationDescriptorBase {

  public EnumerationDescriptor_PermissonEnume() {
    super(0x6ca29f22b4ff46a5L, 0x8ec78f1d723ef329L, 0x6aef70d2f7fde4c2L, "PermissonEnume", "r:8a1306e6-be63-4b5e-801e-6094cad57bfd(UDML.rbac.structure)/7705501538860262594");
  }

  private final EnumerationDescriptor.MemberDescriptor myMember_ALLOW_0 = new EnumerationDescriptor.MemberDescriptor("ALLOW", "1", 0x6aef70d2f7fde4c3L, "r:8a1306e6-be63-4b5e-801e-6094cad57bfd(UDML.rbac.structure)/7705501538860262595");
  private final EnumerationDescriptor.MemberDescriptor myMember_DENY_0 = new EnumerationDescriptor.MemberDescriptor("DENY", "0", 0x6aef70d2f7fde4c4L, "r:8a1306e6-be63-4b5e-801e-6094cad57bfd(UDML.rbac.structure)/7705501538860262596");

  private final EnumerationLiteralsIndex myIndex = EnumerationLiteralsIndex.build(0x6ca29f22b4ff46a5L, 0x8ec78f1d723ef329L, 0x6aef70d2f7fde4c2L, 0x6aef70d2f7fde4c3L, 0x6aef70d2f7fde4c4L);
  private final List<EnumerationDescriptor.MemberDescriptor> myMembers = new EnumerationDescriptorBase.MembersList0(myIndex, myMember_ALLOW_0, myMember_DENY_0);

  @Nullable
  @Override
  public EnumerationDescriptor.MemberDescriptor getDefault() {
    return null;
  }

  @NotNull
  @Override
  public List<EnumerationDescriptor.MemberDescriptor> getMembers() {
    return myMembers;
  }

  @Nullable
  @Override
  public EnumerationDescriptor.MemberDescriptor getMember(@Nullable String memberName) {
    if (memberName == null) {
      return null;
    }
    switch (memberName) {
      case "ALLOW":
        return myMember_ALLOW_0;
      case "DENY":
        return myMember_DENY_0;
    }
    return null;
  }

  @Nullable
  @Override
  public EnumerationDescriptor.MemberDescriptor getMember(long idValue) {
    int index = myIndex.index(idValue);
    if (index == -1) {
      return null;
    }
    return myMembers.get(index);
  }
}
