package UDML.rbac.structure;

/*Generated by MPS */

import jetbrains.mps.smodel.runtime.EnumerationDescriptorBase;
import jetbrains.mps.smodel.runtime.EnumerationDescriptor;
import jetbrains.mps.lang.smodel.EnumerationLiteralsIndex;
import java.util.List;
import org.jetbrains.annotations.Nullable;
import org.jetbrains.annotations.NotNull;

public class EnumerationDescriptor_SoDEnum extends EnumerationDescriptorBase {

  public EnumerationDescriptor_SoDEnum() {
    super(0x6ca29f22b4ff46a5L, 0x8ec78f1d723ef329L, 0x6aef70d2f7fde4dbL, "SoDEnum", "r:8a1306e6-be63-4b5e-801e-6094cad57bfd(UDML.rbac.structure)/7705501538860262619");
  }

  private final EnumerationDescriptor.MemberDescriptor myMember_STATIC_0 = new EnumerationDescriptor.MemberDescriptor("STATIC", "0", 0x6aef70d2f7fde4dcL, "r:8a1306e6-be63-4b5e-801e-6094cad57bfd(UDML.rbac.structure)/7705501538860262620");
  private final EnumerationDescriptor.MemberDescriptor myMember_DYNAMIC_0 = new EnumerationDescriptor.MemberDescriptor("DYNAMIC", "1", 0x6aef70d2f7fde4e9L, "r:8a1306e6-be63-4b5e-801e-6094cad57bfd(UDML.rbac.structure)/7705501538860262633");

  private final EnumerationLiteralsIndex myIndex = EnumerationLiteralsIndex.build(0x6ca29f22b4ff46a5L, 0x8ec78f1d723ef329L, 0x6aef70d2f7fde4dbL, 0x6aef70d2f7fde4dcL, 0x6aef70d2f7fde4e9L);
  private final List<EnumerationDescriptor.MemberDescriptor> myMembers = new EnumerationDescriptorBase.MembersList0(myIndex, myMember_STATIC_0, myMember_DYNAMIC_0);

  @Nullable
  @Override
  public EnumerationDescriptor.MemberDescriptor getDefault() {
    return null;
  }

  @NotNull
  @Override
  public List<EnumerationDescriptor.MemberDescriptor> getMembers() {
    return myMembers;
  }

  @Nullable
  @Override
  public EnumerationDescriptor.MemberDescriptor getMember(@Nullable String memberName) {
    if (memberName == null) {
      return null;
    }
    switch (memberName) {
      case "STATIC":
        return myMember_STATIC_0;
      case "DYNAMIC":
        return myMember_DYNAMIC_0;
    }
    return null;
  }

  @Nullable
  @Override
  public EnumerationDescriptor.MemberDescriptor getMember(long idValue) {
    int index = myIndex.index(idValue);
    if (index == -1) {
      return null;
    }
    return myMembers.get(index);
  }
}
