package UDML.rbac.structure;

/*Generated by MPS */

import jetbrains.mps.lang.smodel.LanguageConceptIndex;
import jetbrains.mps.lang.smodel.LanguageConceptIndexBuilder;
import jetbrains.mps.smodel.adapter.ids.SConceptId;
import org.jetbrains.mps.openapi.language.SAbstractConcept;

public final class LanguageConceptSwitch {
  private final LanguageConceptIndex myIndex;
  public static final int DynamicSeparationOfDuty = 0;
  public static final int Permission = 1;
  public static final int Policy = 2;
  public static final int RBACAnnointern = 3;
  public static final int RbacRoot = 4;
  public static final int Role = 5;
  public static final int Session = 6;
  public static final int SoDConstraint = 7;
  public static final int StaticSeparationOfDuty = 8;

  public LanguageConceptSwitch() {
    LanguageConceptIndexBuilder builder = new LanguageConceptIndexBuilder(0x6ca29f22b4ff46a5L, 0x8ec78f1d723ef329L);
    builder.put(0x1d1947166b439ffaL, DynamicSeparationOfDuty);
    builder.put(0x6aef70d2f7fde4bfL, Permission);
    builder.put(0x6aef70d2f7fde4d5L, Policy);
    builder.put(0x2cd9507b18a0e1b7L, RBACAnnointern);
    builder.put(0x6aef70d2f7fde4f8L, RbacRoot);
    builder.put(0x6aef70d2f7fde4b9L, Role);
    builder.put(0x1d1947166b439ff8L, Session);
    builder.put(0x6aef70d2f7fde4eaL, SoDConstraint);
    builder.put(0x1d1947166b439ffbL, StaticSeparationOfDuty);
    myIndex = builder.seal();
  }

  /*package*/ int index(SConceptId cid) {
    return myIndex.index(cid);
  }

  public int index(SAbstractConcept concept) {
    return myIndex.index(concept);
  }
}
