package UDML.rbac.structure;

/*Generated by MPS */

import jetbrains.mps.smodel.runtime.BaseStructureAspectDescriptor;
import jetbrains.mps.smodel.runtime.ConceptDescriptor;
import jetbrains.mps.smodel.runtime.EnumerationDescriptor;
import java.util.Collection;
import java.util.Arrays;
import org.jetbrains.annotations.Nullable;
import jetbrains.mps.smodel.adapter.ids.SConceptId;
import jetbrains.mps.smodel.runtime.DataTypeDescriptor;
import org.jetbrains.mps.openapi.language.SAbstractConcept;
import jetbrains.mps.smodel.runtime.impl.ConceptDescriptorBuilder2;
import jetbrains.mps.smodel.adapter.ids.PrimitiveTypeId;
import jetbrains.mps.smodel.adapter.ids.MetaIdFactory;

public class StructureAspectDescriptor extends BaseStructureAspectDescriptor {
  /*package*/ final ConceptDescriptor myConceptDynamicSeparationOfDuty = createDescriptorForDynamicSeparationOfDuty();
  /*package*/ final ConceptDescriptor myConceptPermission = createDescriptorForPermission();
  /*package*/ final ConceptDescriptor myConceptPolicy = createDescriptorForPolicy();
  /*package*/ final ConceptDescriptor myConceptRBACAnnointern = createDescriptorForRBACAnnointern();
  /*package*/ final ConceptDescriptor myConceptRbacRoot = createDescriptorForRbacRoot();
  /*package*/ final ConceptDescriptor myConceptRole = createDescriptorForRole();
  /*package*/ final ConceptDescriptor myConceptSession = createDescriptorForSession();
  /*package*/ final ConceptDescriptor myConceptSoDConstraint = createDescriptorForSoDConstraint();
  /*package*/ final ConceptDescriptor myConceptStaticSeparationOfDuty = createDescriptorForStaticSeparationOfDuty();
  /*package*/ final EnumerationDescriptor myEnumerationPermissonEnume = new EnumerationDescriptor_PermissonEnume();
  /*package*/ final EnumerationDescriptor myEnumerationSoDEnum = new EnumerationDescriptor_SoDEnum();
  private final LanguageConceptSwitch myIndexSwitch;

  public StructureAspectDescriptor() {
    myIndexSwitch = new LanguageConceptSwitch();
  }


  @Override
  public void reportDependencies(jetbrains.mps.smodel.runtime.StructureAspectDescriptor.Dependencies deps) {
    deps.extendedLanguage(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, "jetbrains.mps.lang.core");
    deps.extendedLanguage(0xfd381d931dce4228L, 0xba53a4e0ecaf0da2L, "UDML.core");
  }

  @Override
  public Collection<ConceptDescriptor> getDescriptors() {
    return Arrays.asList(myConceptDynamicSeparationOfDuty, myConceptPermission, myConceptPolicy, myConceptRBACAnnointern, myConceptRbacRoot, myConceptRole, myConceptSession, myConceptSoDConstraint, myConceptStaticSeparationOfDuty);
  }

  @Override
  @Nullable
  public ConceptDescriptor getDescriptor(SConceptId id) {
    switch (myIndexSwitch.index(id)) {
      case LanguageConceptSwitch.DynamicSeparationOfDuty:
        return myConceptDynamicSeparationOfDuty;
      case LanguageConceptSwitch.Permission:
        return myConceptPermission;
      case LanguageConceptSwitch.Policy:
        return myConceptPolicy;
      case LanguageConceptSwitch.RBACAnnointern:
        return myConceptRBACAnnointern;
      case LanguageConceptSwitch.RbacRoot:
        return myConceptRbacRoot;
      case LanguageConceptSwitch.Role:
        return myConceptRole;
      case LanguageConceptSwitch.Session:
        return myConceptSession;
      case LanguageConceptSwitch.SoDConstraint:
        return myConceptSoDConstraint;
      case LanguageConceptSwitch.StaticSeparationOfDuty:
        return myConceptStaticSeparationOfDuty;
      default:
        return null;
    }
  }

  @Override
  public Collection<DataTypeDescriptor> getDataTypeDescriptors() {
    return Arrays.asList(myEnumerationPermissonEnume, myEnumerationSoDEnum);
  }

  /*package*/ int internalIndex(SAbstractConcept c) {
    return myIndexSwitch.index(c);
  }

  private static ConceptDescriptor createDescriptorForDynamicSeparationOfDuty() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("UDML.rbac", "DynamicSeparationOfDuty", 0x6ca29f22b4ff46a5L, 0x8ec78f1d723ef329L, 0x1d1947166b439ffaL);
    b.class_(false, false, false);
    // extends: UDML.rbac.structure.Session
    b.super_(0x6ca29f22b4ff46a5L, 0x8ec78f1d723ef329L, 0x1d1947166b439ff8L);
    b.origin("r:8a1306e6-be63-4b5e-801e-6094cad57bfd(UDML.rbac.structure)/2096785263132123130");
    b.version(3);
    b.aggregate("conflictRole", 0x2cd9507b18a0e1d7L).target(0x6ca29f22b4ff46a5L, 0x8ec78f1d723ef329L, 0x6aef70d2f7fde4b9L).optional(true).ordered(true).multiple(true).origin("3231702697239437783").done();
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForPermission() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("UDML.rbac", "Permission", 0x6ca29f22b4ff46a5L, 0x8ec78f1d723ef329L, 0x6aef70d2f7fde4bfL);
    b.class_(false, false, false);
    b.origin("r:8a1306e6-be63-4b5e-801e-6094cad57bfd(UDML.rbac.structure)/7705501538860262591");
    b.version(3);
    b.property("id", 0x6aef70d2f7fde4c0L).type(PrimitiveTypeId.INTEGER).origin("7705501538860262592").done();
    b.property("resource", 0x6aef70d2f7fde4d1L).type(PrimitiveTypeId.STRING).origin("7705501538860262609").done();
    b.property("condition", 0x6aef70d2f7fde4d2L).type(PrimitiveTypeId.STRING).origin("7705501538860262610").done();
    b.property("actions", 0x6aef70d2f7fde4d4L).type(PrimitiveTypeId.STRING).origin("7705501538860262612").done();
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForPolicy() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("UDML.rbac", "Policy", 0x6ca29f22b4ff46a5L, 0x8ec78f1d723ef329L, 0x6aef70d2f7fde4d5L);
    b.class_(false, false, false);
    b.origin("r:8a1306e6-be63-4b5e-801e-6094cad57bfd(UDML.rbac.structure)/7705501538860262613");
    b.version(3);
    b.property("Policyid", 0x6aef70d2f7fde4d6L).type(PrimitiveTypeId.INTEGER).origin("7705501538860262614").done();
    b.property("effect", 0x6aef70d2f7fde4d7L).type(MetaIdFactory.dataTypeId(0x6ca29f22b4ff46a5L, 0x8ec78f1d723ef329L, 0x6aef70d2f7fde4c2L)).origin("7705501538860262615").done();
    b.property("condition", 0x6aef70d2f7fde4d8L).type(PrimitiveTypeId.STRING).origin("7705501538860262616").done();
    b.associate("roles", 0x6aef70d2f7fde4d9L).target(0x6ca29f22b4ff46a5L, 0x8ec78f1d723ef329L, 0x6aef70d2f7fde4b9L).optional(true).origin("7705501538860262617").done();
    b.associate("permissions", 0x6aef70d2f7fde4daL).target(0x6ca29f22b4ff46a5L, 0x8ec78f1d723ef329L, 0x6aef70d2f7fde4bfL).optional(true).origin("7705501538860262618").done();
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForRBACAnnointern() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("UDML.rbac", "RBACAnnointern", 0x6ca29f22b4ff46a5L, 0x8ec78f1d723ef329L, 0x2cd9507b18a0e1b7L);
    b.interface_();
    b.parent(0xfd381d931dce4228L, 0xba53a4e0ecaf0da2L, 0x49e02d1c64bbe825L);
    b.origin("r:8a1306e6-be63-4b5e-801e-6094cad57bfd(UDML.rbac.structure)/3231702697239437751");
    b.version(3);
    b.property("targetNodeRef", 0x2cd9507b18a0e1c5L).type(MetaIdFactory.dataTypeId(0xfd381d931dce4228L, 0xba53a4e0ecaf0da2L, 0x49e02d1c64bbef95L)).origin("3231702697239437765").done();
    b.associate("policyRef", 0x2cd9507b18a0e1c7L).target(0x6ca29f22b4ff46a5L, 0x8ec78f1d723ef329L, 0x6aef70d2f7fde4d5L).optional(true).origin("3231702697239437767").done();
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForRbacRoot() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("UDML.rbac", "RbacRoot", 0x6ca29f22b4ff46a5L, 0x8ec78f1d723ef329L, 0x6aef70d2f7fde4f8L);
    b.class_(false, false, true);
    b.origin("r:8a1306e6-be63-4b5e-801e-6094cad57bfd(UDML.rbac.structure)/7705501538860262648");
    b.version(3);
    b.aggregate("Roles", 0x6aef70d2f7fde4f9L).target(0x6ca29f22b4ff46a5L, 0x8ec78f1d723ef329L, 0x6aef70d2f7fde4b9L).optional(true).ordered(true).multiple(true).origin("7705501538860262649").done();
    b.aggregate("Permission", 0x6aef70d2f7fde4faL).target(0x6ca29f22b4ff46a5L, 0x8ec78f1d723ef329L, 0x6aef70d2f7fde4bfL).optional(true).ordered(true).multiple(true).origin("7705501538860262650").done();
    b.aggregate("Policies", 0x6aef70d2f7fde4fbL).target(0x6ca29f22b4ff46a5L, 0x8ec78f1d723ef329L, 0x6aef70d2f7fde4d5L).optional(true).ordered(true).multiple(true).origin("7705501538860262651").done();
    b.aggregate("SodContrains", 0x6aef70d2f7fde4fcL).target(0x6ca29f22b4ff46a5L, 0x8ec78f1d723ef329L, 0x6aef70d2f7fde4eaL).optional(true).ordered(true).multiple(true).origin("7705501538860262652").done();
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForRole() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("UDML.rbac", "Role", 0x6ca29f22b4ff46a5L, 0x8ec78f1d723ef329L, 0x6aef70d2f7fde4b9L);
    b.class_(false, false, false);
    b.origin("r:8a1306e6-be63-4b5e-801e-6094cad57bfd(UDML.rbac.structure)/7705501538860262585");
    b.version(3);
    b.property("name", 0x6aef70d2f7fde4baL).type(PrimitiveTypeId.STRING).origin("7705501538860262586").done();
    b.property("description", 0x6aef70d2f7fde4bdL).type(PrimitiveTypeId.STRING).origin("7705501538860262589").done();
    b.associate("parents", 0x6aef70d2f7fde4beL).target(0x6ca29f22b4ff46a5L, 0x8ec78f1d723ef329L, 0x6aef70d2f7fde4b9L).optional(true).origin("7705501538860262590").done();
    b.aggregate("permissions", 0x6aef70d2f7fde4ccL).target(0x6ca29f22b4ff46a5L, 0x8ec78f1d723ef329L, 0x6aef70d2f7fde4bfL).optional(true).ordered(true).multiple(true).origin("7705501538860262604").done();
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForSession() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("UDML.rbac", "Session", 0x6ca29f22b4ff46a5L, 0x8ec78f1d723ef329L, 0x1d1947166b439ff8L);
    b.class_(false, false, false);
    b.origin("r:8a1306e6-be63-4b5e-801e-6094cad57bfd(UDML.rbac.structure)/2096785263132123128");
    b.version(3);
    b.property("timeStart", 0x2cd9507b18a0e1cbL).type(PrimitiveTypeId.INTEGER).origin("3231702697239437771").done();
    b.property("timeEnd", 0x2cd9507b18a0e1ccL).type(PrimitiveTypeId.INTEGER).origin("3231702697239437772").done();
    b.property("id", 0x2cd9507b18a0e1cdL).type(PrimitiveTypeId.INTEGER).origin("3231702697239437773").done();
    b.property("minConflictSize", 0x2cd9507b18a0e1d4L).type(PrimitiveTypeId.INTEGER).origin("3231702697239437780").done();
    b.property("scope", 0x2cd9507b18a0e1d5L).type(PrimitiveTypeId.STRING).origin("3231702697239437781").done();
    b.property("enable", 0x2cd9507b18a0e1d8L).type(PrimitiveTypeId.BOOLEAN).origin("3231702697239437784").done();
    b.property("exceptionExpr", 0x2cd9507b18a0e1dbL).type(PrimitiveTypeId.STRING).origin("3231702697239437787").done();
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForSoDConstraint() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("UDML.rbac", "SoDConstraint", 0x6ca29f22b4ff46a5L, 0x8ec78f1d723ef329L, 0x6aef70d2f7fde4eaL);
    b.class_(false, false, false);
    b.origin("r:8a1306e6-be63-4b5e-801e-6094cad57bfd(UDML.rbac.structure)/7705501538860262634");
    b.version(3);
    b.property("id", 0x6aef70d2f7fde4ecL).type(PrimitiveTypeId.INTEGER).origin("7705501538860262636").done();
    b.property("type", 0x6aef70d2f7fde4edL).type(MetaIdFactory.dataTypeId(0x6ca29f22b4ff46a5L, 0x8ec78f1d723ef329L, 0x6aef70d2f7fde4dbL)).origin("7705501538860262637").done();
    b.property("ruleExpr", 0x6aef70d2f7fde4eeL).type(PrimitiveTypeId.STRING).origin("7705501538860262638").done();
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForStaticSeparationOfDuty() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("UDML.rbac", "StaticSeparationOfDuty", 0x6ca29f22b4ff46a5L, 0x8ec78f1d723ef329L, 0x1d1947166b439ffbL);
    b.class_(false, false, false);
    b.origin("r:8a1306e6-be63-4b5e-801e-6094cad57bfd(UDML.rbac.structure)/2096785263132123131");
    b.version(3);
    return b.create();
  }
}
